#Programming Building Blocks, 220920
print("To generate your ID card, please enter the following information:")
fn = input("First name: ")
fn = fn.title()
ln = input("Last name: ")
ln = ln.upper()
email = input("Email Address: ")
email = email.lower()
phone = input("Phone number: ")
jobTitle = input("Job title: ")
jobTitle = jobTitle.title()
idNum = input("ID Number: ")
hair = input("Hair color: ")
hair = hair.title()
eye = input("Eye color: ")
eye = eye.title()
month = input("Month started: ")
month = month.title()
train = input("Been trained? Please type yes or no: ")
train = train.title()
spacer = ("----------------------------------------")

print(f"\n\nThe ID Card is:\n{spacer}\n{ln}, {fn}\n{jobTitle}\nID: {idNum}\n\n{email}\n{phone}")
print(f"{'Hair: '+hair:<25} Eyes: {eye}\n{'Month: '+month:<25} Training: {train}\n{spacer}")